import * as algokit from '@algorandfoundation/algokit-utils';
import { SessionData } from './session';

// This is a mock of the generated client interface
// In a real scenario, this would be generated by `algokit generate`
export interface SessionLedgerClient {
    createSession(args: { sessionId: string; duration: number }): Promise<void>;
    startSession(args: { sessionId: string }): Promise<void>;
    rotateNonce(args: { sessionId: string }): Promise<number>;
    markAttendance(args: { sessionId: string; nonce: number }): Promise<void>;
    getSession(sessionId: string): Promise<SessionData>;
}

// Mock implementation for development when contracts aren't built
export class MockSessionLedgerClient implements SessionLedgerClient {
    private sessions: Map<string, SessionData> = new Map();

    async createSession(args: { sessionId: string; duration: number }): Promise<void> {
        console.log('Mock: Create Session', args);
        this.sessions.set(args.sessionId, {
            sessionId: args.sessionId,
            organizer: 'mock-organizer',
            startTime: Date.now(),
            endTime: Date.now() + args.duration * 60000,
            active: false,
            currentNonce: 0,
            totalAttendees: 0
        });
    }

    async startSession(args: { sessionId: string }): Promise<void> {
        console.log('Mock: Start Session', args);
        const session = this.sessions.get(args.sessionId);
        if (session) session.active = true;
    }

    async rotateNonce(args: { sessionId: string }): Promise<number> {
        console.log('Mock: Rotate Nonce', args);
        const session = this.sessions.get(args.sessionId);
        const newNonce = Math.floor(Math.random() * 1000000);
        if (session) session.currentNonce = newNonce;
        return newNonce;
    }

    async markAttendance(args: { sessionId: string; nonce: number }): Promise<void> {
        console.log('Mock: Mark Attendance', args);
        // Simulate verification
    }

    async getSession(sessionId: string): Promise<SessionData> {
        return this.sessions.get(sessionId) || {
            sessionId: '',
            organizer: '',
            startTime: 0,
            endTime: 0,
            active: false,
            currentNonce: 0,
            totalAttendees: 0
        };
    }
}

export const mockClientInstance = new MockSessionLedgerClient();
